Repository eu-digital-identity-wallet/eudi-web-verifier, pull requests merged in 2024-04, with the labels that each got.

#47 Feature 45
  .gitignore
  .vscode/settings.json
  src/app/core/constants/constants.ts
  src/app/features/home/components/home/home.component.html
  src/app/features/home/components/home/home.component.ts
  src/app/features/home/components/input-scheme/error-state-matcher.ts
  src/app/features/home/components/input-scheme/input-scheme.component.html
  src/app/features/home/components/input-scheme/input-scheme.component.scss
  src/app/features/home/components/input-scheme/input-scheme.component.spec.ts
  src/app/features/home/components/input-scheme/input-scheme.component.ts
  src/app/features/presentation-definition/components/presentation-request/presentation-request.component.html
  src/app/features/verifiable-credential/components/qr-code/qr-code.component.ts
  src/proxy.conf.json
Labels: feature

#48 feat: update PID Presentation Definition object
  src/app/core/data/cbor_fields.ts
  src/app/core/data/pid_presentation_definition.ts
  src/app/core/models/CBORFields.ts
  src/app/features/home/components/home/home.component.spec.ts
  src/app/features/siop-custom/components/create-a-scenario/create-a-scenario.component.html
  src/app/features/siop-custom/components/create-a-scenario/create-a-scenario.component.ts
  src/app/features/siop-custom/models/Constraint.ts
  src/app/features/siop-custom/models/DefinitionPath.ts
  src/app/features/siop-custom/models/InputDescriptors.ts
  src/app/features/siop-custom/models/Presentation.ts
  src/app/features/siop-custom/models/PresentationDefinition.ts
  src/app/shared/elements/body-actions/body-actions.component.spec.ts
  src/app/shared/elements/body-actions/body-actions.component.ts
  src/app/shared/elements/body-actions/body-actions.service.spec.ts
  src/app/shared/elements/body-actions/body-actions.service.ts
  src/app/shared/elements/body-actions/models/modification.ts
  src/app/shared/shared.module.ts
Labels: feature

#49 Adding dependabot configuration.
  .github/dependabot.yml
Labels: feature, dependencies

#51 fix: fix bug on the next button
  src/app/shared/elements/body-actions/body-actions.component.ts
Labels: bug
